### ISSUE TITLE
mac open iaito.app crash

### ISSUE THREAD

**Issue by cxapython** [radareorg/iaito#108]
**Feature Request Description**

Process:               iaito [38547]
Path:                  /private/var/folders/*/iaito.app/Contents/MacOS/iaito
Identifier:            org.radare.iaito
Version:               5.7.6 (5.7.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           iaito [38547]
User ID:               501

Date/Time:             2022-10-13 12:37:03.001 +0800
OS Version:            Mac OS X 10.15.7 (19H1615)
Report Version:        12
Bridge OS Version:     6.1 (19P647)
Anonymous UUID:        B895E615-89BF-5F6C-FC52-E212040BFFDD

Sleep/Wake UUID:       36527CED-4CC1-4A5F-BEE8-13F711701F92

Time Awake Since Boot: 590000 seconds
Time Since Wake:       260000 seconds

System Integrity Protection: disabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libr_hash.dylib
  Referenced from: /private/var/folders/*/iaito.app/Contents/MacOS/iaito
  Reason: image not found

Binary Images:
       0x1058b2000 -        0x105b6dfff +org.radare.iaito (5.7.6 - 5.7.6) <A20E1440-6069-3A59-A683-32159FA73B9E> /var/folders/*/iaito.app/Contents/MacOS/iaito
       0x105d68000 -        0x105fabfff +libr_core.dylib (0) <681AC177-3925-38D7-96ED-3F3D7B576C88> /usr/local/lib/libr_core.dylib
       0x106055000 -        0x10605cffb +libr_config.dylib (0) <545C0B37-F578-3DBB-A3E7-913085EA7E1C> /usr/local/lib/libr_config.dylib
       0x10606b000 -        0x106096fff +libr_debug.dylib (0) <294DAF3E-0958-3453-B4DC-ABBF417438A2> /usr/local/lib/libr_debug.dylib
       0x1060b6000 -        0x10625dffb +libr_bin.dylib (0) <215D0B13-A990-3159-B01B-4A1A6D16E6FA> /usr/local/lib/libr_bin.dylib
       0x106303000 -        0x106b02ff7 +libr_anal.dylib (0) <8CB166BF-DC8F-3F1E-8155-BCB5D1A6F768> /usr/local/lib/libr_anal.dylib
       0x1070e4000 -        0x1070e7ffb +libr_bp.dylib (0) <7751153C-F959-321C-BC63-F9706F8F3A15> /usr/local/lib/libr_bp.dylib
       0x1070fa000 -        0x10710dff7 +libr_egg.dylib (0) <DE854E70-C1FC-3E07-90E7-ED53CB98175C> /usr/local/lib/libr_egg.dylib
       0x10711f000 -        0x107192ffb +libr_asm.dylib (0) <CB6624C3-D087-3186-8E50-5511E1EC1A3B> /usr/local/lib/libr_asm.dylib
       0x1071c7000 -        0x1071cefff +libr_lang.dylib (0) <53F7ED7A-4C80-3838-9653-B2EDFA40F7FA> /usr/local/lib/libr_lang.dylib
       0x1071e3000 -        0x107216ff7 +libr_parse.dylib (0) <91A8B942-2B59-319A-842E-B876A8E27E96> /usr/local/lib/libr_parse.dylib
       0x107233000 -        0x10723aff7 +libr_flag.dylib (0) <908288C0-F70B-318C-9E85-DBD048184EEE> /usr/local/lib/libr_flag.dylib
       0x107249000 -        0x107254fff +libr_reg.dylib (0) <35875F07-42A0-3C97-BDB2-709A36F96ABA> /usr/local/lib/libr_reg.dylib
       0x10726a000 -        0x107271ff7 +libr_search.dylib (0) <BEE3EC89-FAC8-3380-9D67-51AE8D14A971> /usr/local/lib/libr_search.dylib
       0x10727f000 -        0x1072a6ff7 +libr_syscall.dylib (0) <F7BFE27E-9C66-3FCC-BD3E-A85BD9E75374> /usr/local/lib/libr_syscall.dylib
       0x1072eb000 -        0x10731aff7 +libr_fs.dylib (0) <2A80BC9C-E49C-33FA-9C4A-1B45F05F45DA> /usr/local/lib/libr_fs.dylib
       0x10734a000 -        0x1073b5ff3 +libr_io.dylib (0) <FFF1762B-C2B2-32E1-BCFE-1F2567A23E7A> /usr/local/lib/libr_io.dylib
       0x107404000 -        0x107413ff3 +libr_socket.dylib (0) <FF292E0B-6F0C-3372-9FD9-FE9CB80A70BF> /usr/local/lib/libr_socket.dylib
       0x107429000 -        0x107450fff +libr_cons.dylib (0) <9F2455E8-EF06-371D-A7EE-A9AC4FA16BE7> /usr/local/lib/libr_cons.dylib
       0x107474000 -        0x107487ff7 +libr_magic.dylib (0) <9C11C7A8-3564-3C26-A760-F9EEB4FDA121> /usr/local/lib/libr_magic.dylib
       0x10749b000 -        0x1074baff7 +libr_crypto.dylib (0) <BC00A59F-E40D-33CA-86A1-8C9AECF50F7C> /usr/local/lib/libr_crypto.dylib
       0x10c5e5000 -        0x10c677267  dyld (750.7) <0D39D8D9-95DC-39E9-B0C5-8D2204C2427B> /usr/lib/dyld

**Comment by trufae** [comment]
```
Library not loaded: /usr/local/lib/libr_hash.dylib
Referenced from: /private/var/folders/*/iaito.app/Contents/MacOS/iaito
Reason: image not found
```

this means that you didnt installed radare2. iaito is not self contained because it allows you to switch between multiple versions of radare because its abi stable

**Comment by trufae** [comment]
(i'm assuming you are download the mac binary from the release page instead of building it by yourself, right? you'll need to install qt too
