### ISSUE TITLE
Segfault when launching on Ubuntu 22.04 (installed form package)

### ISSUE THREAD

**Issue by DJLevel3** [radareorg/iaito#113]
I just installed Iaito on my Ubuntu Mate system (22.04, kernel version 6.0.0), and I'm getting a segfault. At first I was getting an error with libr_core.so missing, but that was because I hadn't installed dependencies. Once I got those installed, I am now getting a simple `Segmentation fault` (core dumped) error. I'm debugging now, but I wanted to see if this is a new error.

Radare2 runs just fine, if that's important.

**Comment by DJLevel3** [comment]
I'm testing the Flathub package momentarily to see if that works

**Comment by DJLevel3** [comment]
Flatpak install runs fine.

**Comment by ixje** [comment]
same for 5.7.6

**Comment by trufae** [comment]
all that stuff is quite old already, i have fixed many bugs in iaito and r2 since the 5.7.x releases, i tagged the last commit from iaito just in case you need it for building a tarball. a new flatpak will be published when r2-5.8 is out (kind of soon)

**Comment by trufae** [comment]
closing, as flatpak is the recommended way to install on windows and linux for now. budliing it for yourself is always a better option. but we should fix the CI builds at some point
