### ISSUE TITLE
arm64 mac build compatibility 

### ISSUE THREAD

**Issue by 4cecoder** [radareorg/iaito#116]
**Feature Request Description**
scripts currently don't recognize darwin-arm64
would like to build on apple silicone macs

cd iaoto && ./configure

checking build system type... arm64-unknown-darwin
checking host system type... arm64-unknown-darwin
checking target system type... arm64-unknown-darwin
checking for working directories... current
using prefix '/usr/local'
checking for c++ compiler... c++
checking for cpp... cpp
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking for r2... /usr/local/bin/r2
Using PKGCONFIG: /opt/homebrew/bin/pkg-config
checking pkg-config flags for r_core... yes
checking for qmake... no
error: This program is required.

**Comment by trufae** [comment]
Just read the error and fix what it says: "checking for qmake... no"

you need to install qt5
