### ISSUE TITLE
ask to stop current debug session when user saves the project in debug mode 

### ISSUE THREAD

**Issue by hamaney** [radareorg/iaito#119]
When in active debug mode, and the user saves the project, communicate the error to the user in one of two ways:

- show an error dialog
- prompt the user if they want to "stop current debug session and save project"

current in r2 console
```
ERROR: radare2 does not support projects on debugged bins
ERROR: Cannot save project
```

**Comment by trufae** [comment]
this is an easy one. ill take care of this even if i never considered debugging on iaito a stable thing
