### ISSUE TITLE
Release Builds for Windows

### ISSUE THREAD

**Issue by alekasm** [radareorg/iaito#131]
I have a couple of suggestions now that I've probably given up on radare2 and iaito. My issue really stems from the prebuilt releases for iaito (which seems inconsistent).

1. Qt libraries are not distributed with the release
2. Qt library versions were unspecified, and if they were compiled with mingw or msvc (its mingw)
3. The required Qt debug libraries are about a gigabyte
4. I'm now missing libstdc++-6.dll, kind of done going down the missing dll rabbit hole

Honestly this should just be built statically as much as possible, or at least include the libraries. It's kind of frustrating that I'm downloading a release build, but it not only doesn't work out-of-the-box, it needs a lot of effort to get it to work.

**Comment by trufae** [comment]
There are people opening this ticket for the last 3 years. and nobody tried to contribute or fix the ci to handle this. you are welcome to do this, but my c++time for this month is over.

1) the qt libraries are distributed with the release
2) iaito builds with any version of qt5 or qt6. if you want to know the specific version of qt, despite it should be abi stable, you can read the ci logs or yaml file
3) qt is bloated and boring i know
4) just build it for yourself, fix the ci or use the flatpak via wsl on windows works really well.

This is the ticket to handle all those diistribution problems beacuse basically qt doesnt provide a single or usable way to distribute apps, winqtdeploy is used, but doesnt works well, it doesnt even add an icon to the app. macqtdeploy seems abandoned and half done, and linuxqtdeploy is a 3rd party tool that was abandoned 2 years ago.

So imho all those are qt/dist problems, not iaito or radare2 ones. I would be happy if anyone experienced with qt could solve all this, but im afraid that wont happen, and i just spend few mins after every release to see if things has improved but nope, under qt6 its still the same. You can read more in this ticket

https://github.com/radareorg/iaito/issues/93
