### ISSUE TITLE
Error while running make: struct r_arch_plugin_t has no member named __

### ISSUE THREAD

**Issue by Epipeppy** [radareorg/iaito#134]
## Environment

Thu Jun 15 04:20:52 PM MDT 2023
radare2 5.8.9.0 @ linux-x86-64
birth: git.5.8.9 2023-06-15__15:29:01
commit: 5.8.9
options: gpl release -O? cs:5 cl:2 make
iaito: command not found
Linux x86-64

## Description

Just got finished building and installing radare2 and radare2-rlang both from their github pages.  

Having an issue installing Iaito though.  I'm able to run the configure script, but when I run the `make` command, I'm getting errors that say: ` {aka 'struct r_arch_plugin_t'} has no member named __ `
This happens for name, author, version, desc, and license, but not arch or cpus.

The script ends with:
```sh
make[1]:  ***    [Makefile: 3499:  Iaito.o] Error 1
make[1]:  ***    Waiting for unfinished jobs....
make[1]:  Leaving directory '/home/sara/Downloads/iaito/iaito-5.8.6/build'
make:  ***    [Makefile: 46: iaito] Error 2
```

Scrolling back up through my terminal I'm seeing a similar error in the rlang install, but it completed successfully as far as I can tell.

## Test

Following the install instructions:
./configure
make

Images attached: t1 (lists the error in Iaito.cpp) is the Iaito error.  The other is from the rlang install; just showing this to give extra info in case it helps.

![t1](https://github.com/radareorg/iaito/assets/54874325/f75ebd3a-3340-40e4-8a4e-f78ef5385d73)
![t2](https://github.com/radareorg/iaito/assets/54874325/b90556b3-107b-4270-9626-091f542ed735)

**Comment by trufae** [comment]
If you want to use iaito from release use radare from release. Otherwise use iaito from git and r2 from git

**Comment by Epipeppy** [comment]
My apologies for the confusion, I'm new to git and github, didn't realize there was a difference.  Thank you for the explanation, it seems to have installed this time.
