### ISSUE TITLE
The action CI compile release job just skip

### ISSUE THREAD

**Issue by cctv130** [radareorg/iaito#140]
![1693523808427](https://github.com/radareorg/iaito/assets/133784576/6f7f3fa8-bc04-4299-b8ec-f13467cd718e)

**Comment by cctv130** [comment]
![1693524307056](https://github.com/radareorg/iaito/assets/133784576/a89e49c5-efc8-4dee-80e1-fe34583f4ad1)

**Comment by trufae** [comment]
Can you try using words instead of images? I dont get what you are trying to say

**Comment by cctv130** [comment]
> Can you try using words instead of images? I dont get what you are trying to say

I tried to automate the windows build using github's action CI feature, but release skipped the previous job when it was done. Do I need to change anything?

**Comment by trufae** [comment]
The release job only runs when there's a tag in the last commit. You can change this in the yaml. Did it worked?

**Comment by cctv130** [comment]
> The release job only runs when there's a tag in the last commit. You can change this in the yaml. Did it worked?

How should I modify this yaml file? I don't know how to modify the yaml of github's action ci.

**Comment by trufae** [comment]
this is the conditional you need to drop

<img width="1800" alt="Screenshot 2023-09-02 at 13 04 00" src="https://github.com/radareorg/iaito/assets/6431515/feee6ed9-822f-4cd3-80f8-f3fd522e11b7">

**Comment by cctv130** [comment]
> this is the conditional you need to drop
> 
> <img alt="Screenshot 2023-09-02 at 13 04 00" width="1800" src="https://user-images.githubusercontent.com/6431515/265200669-feee6ed9-822f-4cd3-80f8-f3fd522e11b7.png">

thank you ，for my friend.
