### ISSUE TITLE
Debian release packages lack dependency information

### ISSUE THREAD

**Issue by GravisZro** [radareorg/iaito#142]
## Description
I install the latest release and everything seemed to work.  Later I started it up again and it threw a segmentation fault. After reinstalling the package and no progress, I checked the dependencies and found it had none listed at all. This is obviously a problem as I seemed to have upgraded some packages and now iaito is non-functional.

Here is the current package info:
```sh
~$ dpkg --info ~/Downloads/iaito_5.8.8_amd64.deb 
 new Debian package, version 2.0.
 size 1298444 bytes: control archive=1028 bytes.
     288 bytes,     9 lines      control
    1941 bytes,    26 lines      md5sums
 Package: iaito
 Version: 5.8.8
 Section: editors
 Priority: optional
 Architecture: amd64
 Installed-Size: 6032
 Maintainer: pancake <pancake@nopcode.org>
 Description: QT frontend for radare2
  This is the continuation of Iaito after the project forked out so it keeps using radare2 as backend.
```

A proper package would have "Depends" information like this:
```
Depends: libc6 (>= 2.4), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.12.2) | libqt5gui5-gles (>= 5.12.2), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.12.2), libstdc++6 (>= 5)
```

**Comment by GravisZro** [comment]
These should be in your dependency list:
```
radare2 libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5 libqt5svg5
```
Note that you will need to determine version numbers as well.

**Comment by trufae** [comment]
Can you update the CONFIG file from dist/debian with your suggested changee?

**Comment by GravisZro** [comment]
@trufae to do that, you need to have the package versions of the system it's built on. I added a script that is called from CONFIG that should generated the dependency list with the version numbers.

**Comment by trufae** [comment]
Can we close this ticket after merging your pr? I can upload the new deb for testing. Thank you!

**Comment by trufae** [comment]
Done https://github.com/radareorg/iaito/releases/tag/5.8.8

**Comment by trufae** [comment]
let's wait for some testing and feedback before closing the ticket. thanks

**Comment by GravisZro** [comment]
Unfortunately, it didn't work.  I'm looking into the build system because it appears the variable isn't being defined in the makefile.

**Comment by GravisZro** [comment]
OK, so I tracked down the issue and definitively fixed it. Merge the PR, update the deb package, and you can close this issue.

**Comment by GravisZro** [comment]
I made a similar fix for radare itself: https://github.com/radareorg/radare2/pull/22280
