### ISSUE TITLE
Highlight Decompilation

### ISSUE THREAD

**Issue by Boberttt** [radareorg/iaito#145]
**Feature Request Description**
Currently in windows, wsl, and linux, the decompilation is not highlighted, making it very hard to read. It would be very appreciated if you'd add this

**Comment by trufae** [comment]
There are 3 levels of highlighting in iaito.

- disabled (does nothing)
- generic (works with all)
- codemeta (the decompiler needs to implement it)
- 
which one are you using and which option. Aso that depends on the colorscheme. I know its a bit weak the way it currently works but having this into may help me prioriize when i find spare time to care about this

thx

**Comment by Boberttt** [comment]
mb didn't see the option
