### ISSUE TITLE
Makefile ignores `-j` on Linux

### ISSUE THREAD

**Issue by jjdredd** [radareorg/iaito#151]

**Comment by trufae** [comment]
because its running qmake under the hood?

**Comment by jjdredd** [comment]
I found that it has been hard-coded into the Makefile in the iaito target. I believe the makefile has been generated by the configure script

**Comment by trufae** [comment]
The configure script doesnt generate any makefile. Feel free to remove that -j4 and see if the makejobs/makeflags is propagated properly and make a pr. Thanks!

**Comment by jjdredd** [comment]
I've tested changing the jobs number in the line I mentioned and it worked as intended.

**Comment by trufae** [comment]
So make a pr

**Comment by jjdredd** [comment]
fixed in https://github.com/radareorg/iaito/commit/c3409ab2517b593c0c1eb0c98583984309695c5c
