### ISSUE TITLE
make

### ISSUE THREAD

**Issue by andynvkz** [radareorg/iaito#156]
../src/core/Iaito.cpp:2514:20: error: ‘RAnalPlugin’ {aka ‘struct r_anal_plugin_t’} has no member named ‘name’
 2514 |         ret << ap->name;
      |                    ^~~~

**Comment by trufae** [comment]
Which version of r2 do you have?

**Comment by andynvkz** [comment]
> Which version of r2 do you have?

radare2 5.8.9 31591 @ linux-x86-64

**Comment by trufae** [comment]
And you are building iaito from git? Because it all builds fine here and also in the ci

**Comment by trufae** [comment]
My guess is that you are building an old version of iaito (release maybe?) against the git version of r2.

Just clone the repo and build it, i'll cut new releases when r2-5.9 is out
