### ISSUE TITLE
Termux compatability

### ISSUE THREAD

**Issue by Usinganame** [radareorg/iaito#163]
I would love to use radare, but I don't like using the command line for things like that. I looked to iaito as a way out and it couldn't run. It's not in the apt repository and I couldn't compile it from source. This is the best decompile I have found and I cant even use it.

**Comment by trufae** [comment]
Iaito is a desktop app, even if running on termux (which should be possible if you install qt5/6) it wont be handy to use in a phone because the ui is not mobile friendly at all.
