### ISSUE TITLE
Add arm64 .dmg to the list of releases

### ISSUE THREAD

**Issue by aLeuleu** [radareorg/iaito#167]
**Add arm64 .dmg to the list of releases**

Would love to have an arm64`.dmg` to quickly install Iaito on the latest macbooks with arm architecture !

**Comment by trufae** [comment]
Guess I can do a local build for it, but the main blocker here is to have a CI job that installs qt for arm64 on x64

**Comment by trufae** [comment]
almost there. ^^

<img width="197" alt="Screenshot 2024-05-24 at 01 33 11" src="https://github.com/radareorg/iaito/assets/6431515/c795649c-9c15-4d03-95f8-b636db4c5d8e">

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/iaito/releases/tag/5.9.2
