### ISSUE TITLE
Crash when using C locale

### ISSUE THREAD

**Issue by prodrigestivill** [radareorg/iaito#183]
## Environment

```
Mon Sep  2 10:40:01 UTC 2024

radare2 5.9.4 0 @ linux-x86-64
birth: git.5.9.4 2024-08-08__23:50:47
commit: 5.9.4
options: gpl release -O1 cs:5 cl:0 make

iaito 5.9.4

Linux x86_64
```

## Description

Crashes when locale is `C.UTF-8`.
Debugged and found the issue happens in [this line](https://github.com/radareorg/iaito/blob/dc51d5fe1604596d0278bd7cc7d2c589a4ec1671/src/dialogs/WelcomeDialog.cpp#L27).

## Test

```sh
export LANG=C.UTF-8
iaito
```

**Comment by trufae** [comment]
cant repro

**Comment by prodrigestivill** [comment]
It needs to be first run to launch the welcome window.
```sh
mv -v ~/.config/radareorg/iaito.conf ~/.config/radareorg/iaito.conf.bak
```

**Comment by trufae** [comment]
Fixed!
