### ISSUE TITLE
Crash on open Decompiler tab

### ISSUE THREAD

**Issue by prodrigestivill** [radareorg/iaito#203]
## Environment

```console
$ date; iaito.r2 -v; iaito -v; uname -ms
Wed Nov 20 10:16:09 UTC 2024
radare2 5.9.8 0 @ linux-x86-64
birth: git.5.9.8 2024-11-19__12:59:53
commit: 5.9.8
options: gpl release -O1 cs:5 cl:0 make
iaito 5.9.8
Linux x86_64
```

## Description

Crashes when clicking Decompiler tab.

Also as a note, just starting it appears this error:
```
ERROR: Invalid `O` subcommand, try `??`
```

But when clicking the tab `Decompiler (Empty)`  it crashes.

Tested on Snap package and Flatpak.

## Test

Open a binary and click `Decompiler (Empty)` directly as first step.

**Comment by trufae** [comment]
This was fixed in 5.9.9
