### ISSUE TITLE
[FIXED] Release 5.2.0 has somehow broken the decompiler

### ISSUE THREAD

**Issue by xambroz** [radareorg/iaito#36]
## Environment Details

Despite we only fix issues reproducible in git-master branch, it's fine to report issues found in releases. And those will be closed when a new release comes out.

```sh
# copypaste this script into your shell and replace it with the output
iaito -v
date
r2 -v
uname -ms
```
```
$ iaito -v
QCommandLineParser: already having an option named "w"
iaito 0.1.0
$ date
2021-04-17T03:56:08 CEST
$ r2 -v
radare2 5.2.0 0 @ linux-x86-64 git.5.2.0
commit: unknown build: 2021-04-16__00:49:31
```
Failed to parse JSON for command "pdcj @ 4199872": illegal value
(break){"annotations":[{"start":0,"end":27,"offset":4199872,"type":"offset"},{"start":27,"end":36,"offset":4199873,"type":"offset"},{"start":36,"end":47,"offset":4199876,"type":"offset"},{"start":47,"end":86,"offset":4199880,"type":"offset"},{"start":86,"end":158,"offset":4199885,"type":"offset"},{"start":158,"end":193,"offset":4199892,"type":"offset"},{"start":193,"end":219,"offset":4199892,"type":"offset"},{"start":219,"end":226,"offset":4199897,"type":"offset"},{"start":226,"end":237,"offset":4199902,"type":"offset"},{"start":237,"end":247,"offset":4199906,"type":"offset"},{"start":247,"end":272,"offset":4199907,"type":"offset"}],"code":"push rbp      //int main();rbp = rsprsp -= 0x20__main ()     //sym.__main ; sym.__mainrcx = rip + \"Hello World!\" //0x404030 ; const char *s ; str.Hello_World_puts ()       //sym.puts ; sym.puts//int puts(\"Hello World!\")eax = 0rsp += 0x200x004015e2return        //rsp ; rsp\n    "}

## Description
It seems that the iaito 5.2.0 has somehow broken the decompiler feature.
I am geting error: Failed to parse JSON from pdc. Or I get some garbage.
Using the iaito console works for both pdc or pdd so decompiler is there and working in radar2

0) r2pm -ci 
1) run iaito
2) open /bin/false
3) seek to main (s main from console)
4) click to decompiler tab ... not psossible
5) pdc - worked in console
6) pdd - worked in console

**Comment by xambroz** [comment]
![Screenshot from 2021-04-17 04-24-16](https://user-images.githubusercontent.com/723625/115099370-b42f1680-9f35-11eb-9413-fd2b69ffe292.png)

**Comment by trufae** [comment]
This is an issue in r2, not in iaito. https://github.com/radareorg/radare2/issues/18582

**Comment by xambroz** [comment]
r2 5.2.1 released
