### ISSUE TITLE
[FIXED] In 5.2.0 release the list of RIO is empty

### ISSUE THREAD

**Issue by xambroz** [radareorg/iaito#37]
## Environment Details

```sh
# copypaste this script into your shell and replace it with the output
iaito -v
date
r2 -v
uname -ms
```
iaito -v
QCommandLineParser: already having an option named "w"
iaito 0.1.0
date
2021-04-17T04:36:42 CEST
r2 -v
radare2 5.2.0 0 @ linux-x86-64 git.5.2.0
commit: unknown build: 2021-04-16__00:49:31
uname -ms
Linux x86_64

## Description

In the release 5.2.0 the list of RIO plugins is empty. 

![Screenshot from 2021-04-17 04-34-36](https://user-images.githubusercontent.com/723625/115099516-a9c14c80-9f36-11eb-9691-7d494a5f3c16.png)

As a result even the file select dialogue is not displaying any other means accessing data then "file://".

**Comment by trufae** [comment]
Please dont fill issues for the releases. Just do it for git. And yes ;this one is also in my list to be fixed for 5.2.1. Its not fixed in git yet

thanks

**Comment by trufae** [comment]
Fixed in 14afa872e2fb30a44ba4c2e13653c6c0564cfd08 will be available in 5.2.1

**Comment by trufae** [comment]
im fine to keep issues open if they are fixed in git but not in the last release. prefixing the issue title with [FIXED] or [5.2.0] or whatever makes it visually less disturbing to me. we can use labels for that, but the title (or using emojis) is visually nicer i think

**Comment by xambroz** [comment]
Hello pancake ... once there is a fix in a form of commit/PR or new release we can close, no need to keep it open.
I can cherrypick the commit/PR for backporting to the release package.

**Comment by trufae** [comment]
Ill telease this week. Dont spend time backportint all the patches :p
