### ISSUE TITLE
Error on compilation: ‘class QThreadPool’ has no member named ‘setStackSize’

### ISSUE THREAD

**Issue by EmmanuelMess** [radareorg/iaito#40]
## Environment Details

Ubuntu 20.04

```sh
No command iaito

sáb 24 abr 2021 23:52:14 -03

radare2 5.3.0-git 26192 @ linux-x86-64 git.5.2.1
commit: 17d5c547643ea77e69c6e283ad623852a05bc6d2 build: 2021-04-24__23:44:42

Linux x86_64
```

## Description
Error on `make`

```
../src/common/AsyncTask.cpp:87:17: error: ‘class QThreadPool’ has no member named ‘setStackSize’
   87 |     threadPool->setStackSize(R2THREAD_STACK_SIZE);
```

Between all the warning I found that error, and the command returns error 2.

**Comment by trufae** [comment]
Which version of QT are you using?

**Comment by EmmanuelMess** [comment]
> Which version of QT are you using?

I ran `sudo apt install qttools5-dev-tools qt5-default libqt5svg5-dev make`. I get:
```
$ qtdiag | grep "Qt"
Qt 5.9.7 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0) on "xcb" ...
```

**Comment by trufae** [comment]
According to the documentation this method was added in qthreadpool in qt-5.10. I should add an ifdef there or directly call setstacksize in the qthreads because qthread::setstacksize exists even on qt4

**Comment by trufae** [comment]
Fixed in master, thanks!
