### ISSUE TITLE
Unable to install and build from source on M1 mac

### ISSUE THREAD

**Issue by watjurk** [radareorg/iaito#43]
## Environment Details

MacBook Pro (13-inch, M1, 2020)
Big Sur 11.3 (20E232)

```sh
zsh: command not found: iaito
Wed May  5 14:23:31 CEST 2021
radare2 5.2.0 0 @ darwin-arm-64 git.
commit: HEAD build: 2021-04-11__23:39:32
Darwin arm64
```

## Description

When I try to install iaito I am getting a following error:
<img width="255" alt="Screenshot" src="https://user-images.githubusercontent.com/21204727/117140471-bdc9d280-adad-11eb-8e4d-86a675b661bc.png">
Related to: #6 

When I try to build from source I am getting a following error:
```sh
In file included from ../src/dialogs/WriteCommandsDialogs.cpp:1:
In file included from ../src/dialogs/WriteCommandsDialogs.h:5:
../src/core/IaitoCommon.h:8:10: fatal error: 'r_core.h' file not found
#include "r_core.h"
         ^~~~~~~~~~
In file included from ../src/Main.cpp:2:
In file included from ../src/IaitoApplication.h:9:
In file included from ../src/core/MainWindow.h:4:
In file included from ../src/core/Iaito.h:4:
../src/core/IaitoCommon.h:8:10: fatal error: 'r_core.h' file not found
#include "r_core.h"
         ^~~~~~~~~~
In file included from ../src/core/Iaito.cpp:13:
In file included from ../src/common/TempConfig.h:5:
../src/core/IaitoCommon.h:8:10: fatal error: 'r_core.h' file not found
#include "r_core.h"
         ^~~~~~~~~~
In file included from ../src/widgets/DisassemblerGraphView.cpp:2:
In file included from ../src/widgets/DisassemblerGraphView.h:11:
In file included from ../src/widgets/IaitoGraphView.h:12:
In file included from ../src/widgets/GraphView.h:18:
In file included from ../src/core/Iaito.h:4:
../src/core/IaitoCommon.h:8:10: fatal error: 'r_core.h' file not found
#include "r_core.h"
         ^~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:8288: WriteCommandsDialogs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [Makefile:8153: Main.o] Error 1
1 error generated.
make[1]: *** [Makefile:8230: Iaito.o] Error 1
1 error generated.
make[1]: *** [Makefile:8425: DisassemblerGraphView.o] Error 1
make[1]: Leaving directory '/iaito/build'
make: *** [Makefile:53: iaito] Error 2
```

**Comment by trufae** [comment]
Which commands are you using to build to build iaito? I would recommend ./configure;make. Also you will need r2-5.2.1 to use latest iaito release or git (not 5.2.0)

but the issue you are showing seems related to not finding the pkgconfig files or the libraries of r2 in your system. This could be because u have an r2 for x86-64 and that wont link with arm64 iaito, try to build r2 from source (git is 5.3. and its also fine)

i dont have any m1 to try and gha doesnt provide m1macs in the CI. But ideally i may build fat versions of iaito for mac on future releases

**Comment by watjurk** [comment]
I'm using ./configure; make. I've installed r2 with brew and I'm building code from 5.2.2 release. It seams that there is a problem with pkg-config:
```zsh
➜  ~ file $(which r2)    
/opt/homebrew/bin/r2: Mach-O 64-bit executable arm64
➜  ~ pkg-config r2   
➜  ~ 
```

And what about this error while trying to install iaito via .pkg ?

**Comment by trufae** [comment]
try `pkg-config --cflags --libs r_core`

**Comment by trufae** [comment]
can you paste the full build log?

**Comment by watjurk** [comment]
Closing in favour of: #45 and #44
