### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by TechnologyClassroom** [radareorg/iaito#46]
When arriving at your repo for the first time, the about and headers describe the forks that resulted in iaito.  The basics about what iaito does is absent.  Starting off by mentioning reverse engineering would be a great improvement.

**Comment by trufae** [comment]
Sounds good. I have recently updated the readme in the radare project, do this one looks good to you? Feel free to submit a pr updating/changing whatever you see.

I'll update the readme of iaito this week.

Thanks!

**Comment by TechnologyClassroom** [comment]
The header of this [older README is descriptive and helps understand what the project is](https://github.com/trufae/iaito/blob/master/README.md).

> A Qt and C++ GUI for radare2 reverse engineering framework

**Comment by trufae** [comment]
Thanks for confirming :)
