### ISSUE TITLE
iaito startup error

### ISSUE THREAD

**Issue by dniraw** [radareorg/iaito#47]
## Environment Details
Pretty much out of the box kali distro. 

iaito: symbol lookup error: iaito: undefined symbol: r_codemeta_free

![iaito](https://user-images.githubusercontent.com/86892536/124365063-9d828c80-dc13-11eb-8d4a-eed3195991ad.png)

I've combed through the dependencies to make sure those weren't an issue, but it doesn't seem like there's anything documented on this issue?

**Comment by trufae** [comment]
This symbol is defined in libr_anal, so my guess is that iaito is loading that lib from somewhere else from an older installation or something

**Comment by trufae** [comment]
If you are using kali its probably caused by the debian package of r2 not properly purged
