### ISSUE TITLE
Missing steps in README for Windows (release 5.3.1)

### ISSUE THREAD

**Issue by MarwanNour** [radareorg/iaito#54]
## Environment Details

OS: Windows 10 

```
.\iaito.exe -v
QCommandLineParser: already having an option named "w"
iaito 5.2.2
date
10 August, 2021 11:28:58 PM
.\radare2.exe -v
radare2 5.3.1 1 @ windows-x86-64 git.5.3.1
commit: d894f967e857a1cfa84144eb4bc0bdc87c540eee build: Tue 06/15/2021__10:11:04.68
```
## Description

The issue with the Windows release 5.3.1 is that it's missing some files that are inside the radare2 repository. When I ran  `iaito.exe`, it gave me a few errors saying some `.dll` files were missing. 
I fixed it by:
- copying the contents of the `bin/` directory of radare2 into the same directory as `iaito.exe`
- copying the directory `share/` of radare2 into the same directory as `iaito.exe`

I think these two instructions would be helpful to put in the README.

**Comment by trufae** [comment]
Can you send a pull request with the suggested changes? That sounds like a legit change to me

**Comment by MarwanNour** [comment]
Yes of course.

**Comment by trufae** [comment]
Thanks!
