### ISSUE TITLE
5.3.1 pkg doesn't unzip. 5.2.2 pkg just opens and nothing happened. 5.2.0 throws an error. Building from source fails.

### ISSUE THREAD

**Issue by vadimszzz** [radareorg/iaito#58]
<img width="471" alt="Screenshot 2021-09-14 at 11 36 11 AM" src="https://user-images.githubusercontent.com/88857748/133224639-531dc8f1-b5b4-4b3a-9dfc-40382863ce45.png">

<img width="374" alt="Screenshot 2021-09-14 at 11 38 00 AM" src="https://user-images.githubusercontent.com/88857748/133225324-8fa1074f-3561-4626-a6f9-620b31156505.png">

<img width="370" alt="Screenshot 2021-09-14 at 11 42 02 AM" src="https://user-images.githubusercontent.com/88857748/133225447-c31ef460-a760-44fa-911c-5d81bc8a6ddc.png">

<img width="856" alt="Screenshot 2021-09-14 at 11 44 15 AM" src="https://user-images.githubusercontent.com/88857748/133225918-bae9ce9a-cde0-445f-9260-1d2a9ae98444.png">

I can't install iaito 😥

**Comment by vadimszzz** [comment]
Built successfully

**Comment by cohall-2020** [comment]
> Built successfully

How did you resolve this?  I'm having the same issue.

**Comment by vadimszzz** [comment]
> > Built successfully
> 
> How did you resolve this? I'm having the same issue.

make
make run

**Comment by trufae** [comment]
After 5.4.2 i will update that build. The invalid pkg issue is fixed in master but didnt uploaded new builds after that.
