### ISSUE TITLE
libr_core.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kakiking** [radareorg/iaito#59]
Evironment:
Arch Linux (completely up to date)
iaito + radare2 installed from git

```
[kakidev@arch iaito]$ make run
build/iaito
build/iaito: error while loading shared libraries: libr_core.so: cannot open shared object file: No such file or directory
make: *** [Makefile:88: run] Fehler 127
[kakidev@arch iaito]$ 
```

**Comment by radare** [comment]
How did u build r2 and how iaito? It looks like iaito should add support for —with-rpath otherwise it wont find the libs if they are in /usr/local if your system is not configured properly

**Comment by Kakiking** [comment]
I just did ```
./configure
make
make install
```

**Comment by Kakiking** [comment]
I tried adding `/usr/local` to `/etc/ld.so.conf` and then running `ldconfig`, but it still can't find it.

**Comment by trufae** [comment]
The path is /usr/local/lib

**Comment by Kakiking** [comment]
Oh.
