### ISSUE TITLE
Missing DLLs on run

### ISSUE THREAD

**Issue by Qardruss** [radareorg/iaito#63]
I run Iaito and I've copied all the files over, but it says some DLLs are missing.
Here's a list of the missing DLLs:
- r_core.dll
- r_config.dll
- r_cons.dll
- r_io.dll

**Comment by trufae** [comment]
Those libs are from r2. You have to download the version of r2 you want and unzip the libs in the same folder. This way iaito is not tied to one build of r2 and you can add and reuse all the plugins shipped by r2 instead of having a single blob with cutter
