### ISSUE TITLE
Missing operands

### ISSUE THREAD

**Issue by subdesign** [radareorg/iaito#66]
## Environment

iaito 5.5.0
Fri Jan 21 16:30:05 CET 2022
radare2 5.5.5 27272 @ darwin-x86-64 git.5.5.4
commit: 85173c6b16243fce3fec1319a8b1929075d25f0a build: 2022-01-21__12:43:57
Darwin x86_64
qt@5: stable 5.15.2

## Description
I don't have operands in the disassembly view, as you see on the picture:

<img width="451" alt="Screenshot 2022-01-21 at 16 31 37" src="https://user-images.githubusercontent.com/691695/150554443-ec56cb3b-fe18-46a1-acd4-cb2df58ddfe8.png">

I tried different binaries.

**Comment by trufae** [comment]
It is happening the same when running r2 from the shell? Which archs happen?

**Comment by trufae** [comment]
I can repro. Will look into that

**Comment by xambroz** [comment]
> It is happening the same when running r2 from the shell?
no r2 is fine (currently r2 5.6.4)
![image](https://user-images.githubusercontent.com/723625/156523965-827cab62-5475-49a7-bf17-2ecd3fbe1d03.png)

**Comment by trufae** [comment]
Fixed in master. its a bug in r2, but has been workarounded in iaito. r2-5.6.6 will come with the proper fix
