### ISSUE TITLE
Decompiler not working

### ISSUE THREAD

**Issue by anthraxx** [radareorg/iaito#73]
## Environment Details

```
iaito 5.5.0 24a2eba21c43f42aa4535278be20ff7e957c884d
radare2 5.6.6
r2ghidra a4ba1ddc85c84a98df1d39fe6c611894daa97474
ghidra-native e45b661d59978b371e30a5540064a31e6ea647f0
```

## Description

Decompiler view loads forever and remains empty. `pdg` command works flawlessly in native `r2`.

**Comment by trufae** [comment]
Iaito uses pdgj, which prints the decompilation in json format. Can you try this? Qt/c++ is ultra slow to load this json, as from my checks this was 80% of the time spent in rendering the output of pdg in iaito.

but now that r2 and r2g are out i'll check this out during the weekend. It shouldnt be hard to fix. Thanks for reporting

**Comment by anthraxx** [comment]
`pdgj` also works and returns basically instantly. In Iaito it doesn't matter how long I wait, i grabbed a coffee and a tiny test method still didn't show any results in Iaito (cpu usage 0%).

**Comment by trufae** [comment]
that sounds like a deadlock to me 💀🔒

**Comment by yechs** [comment]
I've encountered the same problem also on `iaito 5.5.0 24a2eba`

Both `pdg` and `pdgj` works within `r2` commandline but not in iaito

**Comment by hacker-jak** [comment]
Same issue here, latest builds and no iaito decompiler output.

**Comment by trufae** [comment]
I have local fixes for this. Will push soon

**Comment by trufae** [comment]
Should be fixed now
