### ISSUE TITLE
Symbol Lookup Error on Startup

### ISSUE THREAD

**Issue by Schweini07** [radareorg/iaito#75]
When starting iaito on my Manjaro Linux machine I get this error:
`iaito: symbol lookup error: iaito: undefined symbol: _ZN6PySide16fillQtPropertiesEP7_objectPK11QMetaObjectS1_PPKcj`

The program was installed through pacman, so I would have expected it to work out of the box, but something's seemingly wrong.

**Comment by trufae** [comment]
Sounds like a problem in the arch package
