### ISSUE TITLE
Cannot make iaito

### ISSUE THREAD

**Issue by Billy1900** [radareorg/iaito#78]
## Environment Details

Despite we only fix issues reproducible in git-master branch, it's fine to report issues found in releases. And those will be closed when a new release comes out.

```sh
# copypaste this script into your shell and replace it with the output
iaito: command not found
Wed 11 May 2022 04:07:20 PM EDT
WARN: r_th_lock_enter: assertion 'thl' failed (line 94)
WARN: r_th_lock_leave: assertion 'thl' failed (line 132)
WARN: r_th_lock_enter: assertion 'thl' failed (line 94)
WARN: r_th_lock_enter: assertion 'thl' failed (line 94)
WARN: r_th_lock_leave: assertion 'thl' failed (line 132)
WARN: r_th_lock_leave: assertion 'thl' failed (line 132)
WARN: r_th_lock_enter: assertion 'thl' failed (line 94)
WARN: r_th_lock_leave: assertion 'thl' failed (line 132)
WARN: r_th_lock_enter: assertion 'thl' failed (line 94)
WARN: r_th_lock_leave: assertion 'thl' failed (line 132)
radare2 5.6.9 27963 @ linux-x86-64 git.wip)
commit: 35d3d75ef12b57b4dccb6523e08b51eaedffdbcc build: 2022-05-11__15:59:01
Linux x86_64
```

## Description

When I make, it told me the error:
```
../src/core/Iaito.cpp:2769:16: error: ‘r_bin_get_relocs_list’ was not declared in this scope; did you mean ‘r_bin_get_relocs’?
 2769 |  RList *list = r_bin_get_relocs_list(core->bin);
      |                ^~~~~~~~~~~~~~~~~~~~~
      |                r_bin_get_relocs

make[1]: *** [Makefile:23782: Iaito.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/billy/Desktop/iaito/build'
make: *** [Makefile:53: iaito] Error 2
```

**Comment by trufae** [comment]
Use r2 from release in case you care about stable behaviours. This is r2 from git and its known to break iaito

**Comment by Billy1900** [comment]
So now I clone this repo `git clone --recurse-submodules https://github.com/radareorg/iaito.git` and run `bash radare2/sys/install.sh --disable-threads`, the another error comes:
```
thread.c:135:2: error: unknown type name ‘cpu_set_t’
  135 |  cpu_set_t c;
      |  ^~~~~~~~~
```

**Comment by trufae** [comment]
I have local fixes for the build and the deadlocks, i'll cleanup and commit when ready. 

The radare submodule is something i want to get rid, because iaito is suposed to use your system installation of r2 and reuse all of its plugins instead of shipping a specific old/stable version. It gives more flexibility and helps to push upstream

**Comment by trufae** [comment]
My patches allow to use r2 build with threads support. So no special configuration will be required

**Comment by Billy1900** [comment]
> I have local fixes for the build and the deadlocks, i'll cleanup and commit when ready.
> 
> The radare submodule is something i want to get rid, because iaito is suposed to use your system installation of r2 and reuse all of its plugins instead of shipping a specific old/stable version. It gives more flexibility and helps to push upstream

I am sorry that I do not fully get what you mean? How do I tackle this issue?

**Comment by Billy1900** [comment]
Here are my solution:
1) `git clone https://github.com/radareorg/iaito.git`
2) and in iaito directory, `git clone https://github.com/radareorg/radare2.git`, and then compile the radare from https://github.com/radareorg/radare2, my version is 5.6.9 (current is the master)
3) `bash radare2/sys/install.sh --disable-threads`
4) then Follow the readme to install QT and configure & make.
