### ISSUE TITLE
The highlighted? text appears  to be completely black and thus unreadable.

### ISSUE THREAD

**Issue by jjdredd** [radareorg/iaito#86]
```
iaito 5.7.0
radare2 5.7.1 28228 @ linux-x86-64 git.5.7.0-111-g698a2cf7a
commit: 698a2cf7af8740bcb6631dd8beb7d613e46f5a22 build: 2022-06-11__18:45:15
Linux x86_64
```

![bug](https://user-images.githubusercontent.com/4748239/173954684-1d94c176-7bd8-4264-8292-ca46a01be04f.png)

**Comment by trufae** [comment]
Change the theme. That may fix the issue, can you confirm? Or run the "eco gb" command in the iaito console

**Comment by jjdredd** [comment]
On dark themes it looks ok, the bug seems to occur for light themes.

**Comment by trufae** [comment]
The color themes come from r2. Can you edit them system wide and submit a fix if thats the case i assume the white theme is setting a bfcolor for those types

**Comment by trufae** [comment]
fixed. thanks

**Comment by jjdredd** [comment]
Thanks, seems to be working fine.
