### ISSUE TITLE
Unable to build on NixOS

### ISSUE THREAD

**Issue by dschrempf** [radareorg/iaito#90]
I am trying to build iaito on NixOS, and I fail because the build script does not find `r_core.h`. However, `r_core.h` is readily available when executing `pkg-config --cflags r_core` in the build environment.

Output of `pkg-config --cflags r_core`:
```
 + pkg-config --cflags r_core
-I/nix/store/a6al83r6rr8j247q1bqis496knlywmzx-radare2-5.7.0/include/libr -I/nix/store/i3kar1gax8ji9v491hpb5iv115ja5lph-openssl-1.1.1o-dev/include -I/nix/store/1cmw9z2sqab115w4vpcpkya6i92syv0x-capstone-4.0.2/include/capstone -I/nix/store/a6al83r6rr8j247q1bqis496knlywmzx-radare2-5.7.0/include/libr -I/nix/store/a6al83r6rr8j247q1bqis496knlywmzx-radare2-5.7.0/include/libr/sdb
```
`r_core.h` is available in `.../include/libr`.

Complete [build.log](https://github.com/radareorg/iaito/files/8947928/build.log).

**Comment by trufae** [comment]
should be fixed now, sorry for not answering before
