### ISSUE TITLE
make run crash on ubuntu 22.04

### ISSUE THREAD

**Issue by vricosti** [radareorg/iaito#94]
## Environment Details

iaito : commande introuvable
sam. 16 juil. 2022 21:32:53 CEST
radare2 5.7.5 28539 @ linux-x86-64 git.5.7.4-52-g10a2fc99d
commit: 10a2fc99d80beb8e0c2cd8dedb209127afb06f2d build: 2022-07-16__21:19:34
Linux x86_64

## Description

when i run make run I get a crash:

```
rarun2 libpath=/usr/local/lib program=build/iaito
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Loading translations path /home/vince/.local/share/iaito/translations
Loading translations path /usr/share/qt5/translations
eco: cannot open colorscheme profile (/home/vince/iaito/cutter)
Plugins are loaded from "/home/vince/.local/share/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/usr/share/ubuntu/radareorg/iaito/plugins"
Plugins are loaded from "/usr/local/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/share/radareorg/iaito/plugins"
Plugins are loaded from "/var/lib/snapd/desktop/radareorg/iaito/plugins"
make: *** [Makefile:81: run] Erreur de segmentation (core dump créé)
```

**Comment by jujuo0o** [comment]
I'm also getting the same error. 
`make build` works fine, but when i do `make run` i get the following error:
```
rarun2 libpath=/usr/local/lib program=build/iaito
ERROR: eco: cannot open colorscheme profile (/home/USER/iaito/cutter)
Plugins are loaded from "/home/USER/.local/share/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/usr/share/xfce4/radareorg/iaito/plugins"
Plugins are loaded from "/usr/local/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/share/radareorg/iaito/plugins"
Plugins are loaded from "/var/lib/snapd/desktop/radareorg/iaito/plugins"
make: *** [Makefile:71: run] Segmentation fault`
```
running `sudo dmesg` shows the following error message:
```
[10614.682108] iaito[104724]: segfault at 2980 ip 0000559c7dc14bc7 sp 00007fffe45752c8 error 4 in iaito[559c7db4b000+1da000]
[10614.682123] Code: f3 ff 48 89 5d 20 48 83 c4 18 5b 5d 41 5c 41 5d c3 49 89 c5 e9 5c 65 f4 ff 66 2e 0f 1f 84 00 00 00 00 00 48 8b 47 20 48 8b 10 <8b> 42 0c 2b 42 08 c3 66 90 b8 06 00 00 00 c3 66 2e 0f 1f 84 00 00
```

**Comment by diabolist** [comment]
Same issue on Kali (on Parallels):
```rarun2 libpath=/usr/local/lib program=build/iaito
libGL error: pci id for fd 6: 1ab8:0010, driver (null)
pci id for fd 7: 1ab8:0010, driver (null)
ERROR: eco: cannot open colorscheme profile (/home/rdh/Software/iaito/cutter)
Plugins are loaded from "/home/rdh/.local/share/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/usr/local/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/share/radareorg/iaito/plugins"
make: *** [Makefile:71: run] Segmentation fault```

**Comment by ibexnet** [comment]
same for me on Ubuntu 22.04.1 LTS kernel 5.15.0-47-generic.
make without errors.
make run:
``
make run           
rarun2 libpath=/usr/local/lib program=build/iaito
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
ERROR: eco: cannot open colorscheme profile (/home/user/.local/src/iaito/cutter)
WARN: This node is not boolean
WARN: r_config_set_b: assertion 'false' failed (line 557)
Plugins are loaded from "/home/user/.local/share/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/home/user/.local/share/flatpak/exports/share/radareorg/iaito/plugins"
Plugins are loaded from "/var/lib/flatpak/exports/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/local/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/share/radareorg/iaito/plugins"
Plugins are loaded from "/var/lib/snapd/desktop/radareorg/iaito/plugins"
make: *** [Makefile:71: run] Segmentation fault (core dumped)
``

**Comment by trufae** [comment]
Please try again with latest master

**Comment by rdhoole** [comment]
Seems to have fixed it. Thanks.

**Comment by ibexnet** [comment]
Confirm that latest master fix the issue
thanks!
